### PR TITLE
Create beacon

### LINKED ISSUE #14: Create Beacon UI
Mirror wireframe (screen 13). 

Create Beacon screen should be accessible through the pink fab on the home screen

Don't add the warning message to discard changes per Vibha's comments

### PR DESCRIPTION
**Pull request by dyzhu12**
Fixes #14 

image
image

### CODE REVIEW

**Comment by dyzhu12** [comment]
Missing the 'finish' arrow at the top right

**Comment by dyzhu12** [comment]
Add 'Mark Location On Map' to gmap fragment

**Comment by dyzhu12** [comment]
Added send button

image

**Comment by lyoung16** [comment]
:+1:

**Pull request merged**
